#!/bin/bash
#
# Upload raw content files to a TAK Server Device Profile via the admin API.
#
# Why this exists: TAK Server's Device Profile Manager stores whatever you
# upload as an opaque blob, then wraps every file attached to a profile into
# a *brand new* Mission Package at delivery time (with onReceiveImport=true
# and onReceiveDelete=true set correctly). If you instead upload an
# already-built Mission Package .zip, the server nests it unchanged inside
# its own wrapper -- the inner zip ends up on the ATAK device as a
# persistent, user-deletable "Data Package" with none of the delete
# protection. See DEVICE_PROFILES.md for the full writeup.
#
# This script uploads RAW content files directly (config.pref, an icon-set
# zip, individual map source .xml files, plugin .apk + plugin.xml, terrain
# .json manifests, etc.) -- never pre-built Mission Package .zip files.
#
# The Device Profile API has no bulk/multipart upload endpoint (PUT
# .../file is one file per call), so this script loops over the given files
# and issues one PUT per file. Re-running the script is safe: any existing
# file on the profile with the same name is deleted before the new content
# is uploaded, so profiles can be updated in place without accumulating
# duplicates.
#
# Usage:
#   upload-device-profile.sh --server <url> (--cert <pem> --key <key> [--key-pass <pass>] | --p12 <file> [--p12-pass <pass>])
#                             --profile <name> [--type Enrollment|Connection|Tool]
#                             [--group <name> [--group <name> ...] | --all-groups]
#                             <file-or-dir> [<file-or-dir> ...]
#
# Positional arguments may be individual files or directories. When a
# directory is given, every regular file directly inside it is uploaded
# (non-recursive; subdirectories such as a MANIFEST/ folder are ignored).
#
# A note on --p12: the admin.p12 generated by TAK Server (and stored in
# Secrets Manager as "<StackName>/TAK-Server/Admin-Cert") is PKCS12 with
# legacy RC2-40-CBC encryption, which curl's OpenSSL backend generally
# cannot load directly -- --p12 will fail with curl exit code 58. If that
# happens, convert it to --cert/--key instead:
#   openssl pkcs12 -in admin-cert.p12 -legacy -passin pass:atakatak \
#     -clcerts -nokeys -out admin.pem
#   openssl pkcs12 -in admin-cert.p12 -legacy -passin pass:atakatak \
#     -nocerts -nodes -out admin.key
# then pass --cert admin.pem --key admin.key. (atakatak is the default p12
# export password used by TAK Server's makeCert.sh / start-tak.sh.)
#
# Examples:
#   # Push standard ATAK settings to the enrollment profile
#   ./upload-device-profile.sh --server https://tak.demo.tak.nz:8443 \
#     --cert /opt/tak/certs/files/admin.pem --key /opt/tak/certs/files/admin.key \
#     --profile TAK-NZ-Enrollment --type Enrollment --all-groups \
#     standard-settings/config.pref
#
#   # Push every map source .xml in a maps-package template directory, plus
#   # an icon set zip and a terrain manifest, to the connection profile
#   ./upload-device-profile.sh --server https://tak.demo.tak.nz:8443 \
#     --p12 ./admin-cert.p12 --p12-pass atakatak \
#     --profile TAK-NZ-Connection --type Connection --all-groups \
#     ../utils-infra/tileserver-helper/maps/template \
#     "../iconset-nzem-symbology/datapackage/iconsets/GEMA NZEM Symbology Set.zip" \
#     ./elevation-manifest.json
#
set -euo pipefail

SERVER=""
CERT_PATH=""
KEY_PATH=""
KEY_PASS=""
P12_PATH=""
P12_PASS=""
PROFILE=""
PROFILE_TYPE=""
ALL_GROUPS=false
declare -a PROFILE_GROUPS=()
declare -a INPUT_PATHS=()

usage() {
    sed -n '2,62p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
        --server) SERVER="$2"; shift 2 ;;
        --cert) CERT_PATH="$2"; shift 2 ;;
        --key) KEY_PATH="$2"; shift 2 ;;
        --key-pass) KEY_PASS="$2"; shift 2 ;;
        --p12) P12_PATH="$2"; shift 2 ;;
        --p12-pass) P12_PASS="$2"; shift 2 ;;
        --profile) PROFILE="$2"; shift 2 ;;
        --type) PROFILE_TYPE="$2"; shift 2 ;;
        --group) PROFILE_GROUPS+=("$2"); shift 2 ;;
        --all-groups) ALL_GROUPS=true; shift ;;
        -h|--help) usage ;;
        --) shift; break ;;
        -*)
            echo "Error: unknown option '$1'" >&2
            usage
            ;;
        *)
            INPUT_PATHS+=("$1")
            shift
            ;;
    esac
done
INPUT_PATHS+=("$@")

if [ -z "$SERVER" ] || [ -z "$PROFILE" ] || [ ${#INPUT_PATHS[@]} -eq 0 ]; then
    echo "Error: --server, --profile, and at least one file/directory are required" >&2
    usage
fi

if [ -z "$P12_PATH" ] && { [ -z "$CERT_PATH" ] || [ -z "$KEY_PATH" ]; }; then
    echo "Error: provide either --p12 <file> or both --cert <pem> and --key <key>" >&2
    usage
fi

if [ -n "$PROFILE_TYPE" ] && [[ ! "$PROFILE_TYPE" =~ ^(Enrollment|Connection|Tool)$ ]]; then
    echo "Error: --type must be one of Enrollment, Connection, Tool" >&2
    exit 1
fi

# Build the curl client-cert arguments once
declare -a CERT_ARGS=()
if [ -n "$P12_PATH" ]; then
    if [ ! -f "$P12_PATH" ]; then
        echo "Error: p12 file not found: $P12_PATH" >&2
        exit 1
    fi
    CERT_ARGS=(--cert-type P12 --cert "${P12_PATH}:${P12_PASS}")
else
    if [ ! -f "$CERT_PATH" ] || [ ! -f "$KEY_PATH" ]; then
        echo "Error: cert or key file not found ($CERT_PATH / $KEY_PATH)" >&2
        exit 1
    fi
    CERT_ARGS=(--cert "$CERT_PATH" --key "$KEY_PATH")
    if [ -n "$KEY_PASS" ]; then
        CERT_ARGS+=(--pass "$KEY_PASS")
    fi
fi

BASE_URL="${SERVER%/}/Marti/api/device/profile"

# Resolve positional args (files and directories) into a flat file list
declare -a FILES=()
for p in "${INPUT_PATHS[@]}"; do
    if [ -d "$p" ]; then
        while IFS= read -r -d '' f; do
            FILES+=("$f")
        done < <(find "$p" -maxdepth 1 -type f -print0 | sort -z)
    elif [ -f "$p" ]; then
        FILES+=("$p")
    else
        echo "Error: no such file or directory: $p" >&2
        exit 1
    fi
done

if [ ${#FILES[@]} -eq 0 ]; then
    echo "Error: no files found to upload" >&2
    exit 1
fi

# URL-encode a path segment / query value
urlencode() {
    jq -rn --arg v "$1" '$v|@uri'
}

echo "Server:  $SERVER"
echo "Profile: $PROFILE"
[ -n "$PROFILE_TYPE" ] && echo "Type:    $PROFILE_TYPE"
echo "Files:   ${#FILES[@]}"
echo

PROFILE_ENC=$(urlencode "$PROFILE")

# --- Step 1: create the profile if it doesn't already exist ---------------
echo "Ensuring profile '${PROFILE}' exists..."
create_http_code=$(curl -sk "${CERT_ARGS[@]}" -o /dev/null -w "%{http_code}" \
    -X POST "${BASE_URL}/${PROFILE_ENC}")

case "$create_http_code" in
    201) echo "  Created new profile" ;;
    200) echo "  Profile already exists" ;;
    *)
        echo "Error: failed to create/verify profile (HTTP ${create_http_code})" >&2
        exit 1
        ;;
esac

# --- Step 2: fetch the profile so we have its id, then update metadata ----
if [ -n "$PROFILE_TYPE" ] || [ "$ALL_GROUPS" = true ] || [ ${#PROFILE_GROUPS[@]} -gt 0 ]; then
    echo "Updating profile metadata..."
    profile_json=$(curl -sk "${CERT_ARGS[@]}" -X GET "${BASE_URL}/${PROFILE_ENC}")

    if [ "$ALL_GROUPS" = true ]; then
        groups_json='["APPLY_TO_ALL_GROUPS"]'
    elif [ ${#PROFILE_GROUPS[@]} -gt 0 ]; then
        groups_json=$(printf '%s\n' "${PROFILE_GROUPS[@]}" | jq -R . | jq -s .)
    else
        groups_json=$(echo "$profile_json" | jq '.data.groups // []')
    fi

    updated_json=$(echo "$profile_json" | jq \
        --arg type "${PROFILE_TYPE:-}" \
        --argjson groups "$groups_json" \
        '.data
         | if $type != "" then .type = $type else . end
         | .groups = $groups')

    update_http_code=$(curl -sk "${CERT_ARGS[@]}" -o /dev/null -w "%{http_code}" \
        -X PUT "${BASE_URL}/${PROFILE_ENC}" \
        -H "Content-Type: application/json" \
        --data "$updated_json")

    if [ "$update_http_code" != "200" ]; then
        echo "Error: failed to update profile metadata (HTTP ${update_http_code})" >&2
        exit 1
    fi
    echo "  Metadata updated"
fi

# --- Step 3: remove any existing file(s) on the profile with the same ----
# --- name, then upload the new content ------------------------------------
existing_files_json=$(curl -sk "${CERT_ARGS[@]}" -X GET "${BASE_URL}/${PROFILE_ENC}/files")

uploaded=0
for f in "${FILES[@]}"; do
    filename=$(basename "$f")
    filename_enc=$(urlencode "$filename")

    existing_ids=$(echo "$existing_files_json" | jq -r \
        --arg name "$filename" '.data[]? | select(.name == $name) | .id')

    if [ -n "$existing_ids" ]; then
        while IFS= read -r id; do
            [ -z "$id" ] && continue
            del_code=$(curl -sk "${CERT_ARGS[@]}" -o /dev/null -w "%{http_code}" \
                -X DELETE "${BASE_URL}/${PROFILE_ENC}/file/${id}")
            if [ "$del_code" != "200" ]; then
                echo "  Warning: failed to delete existing file id ${id} for '${filename}' (HTTP ${del_code})" >&2
            fi
        done <<< "$existing_ids"
    fi

    upload_code=$(curl -sk "${CERT_ARGS[@]}" -o /dev/null -w "%{http_code}" \
        -X PUT "${BASE_URL}/${PROFILE_ENC}/file?filename=${filename_enc}" \
        -H "Content-Type: application/octet-stream" \
        --data-binary "@${f}")

    if [ "$upload_code" = "200" ]; then
        echo "  Uploaded: ${filename}"
        uploaded=$((uploaded + 1))
    else
        echo "  Failed:   ${filename} (HTTP ${upload_code})" >&2
        exit 1
    fi
done

echo
echo "Done. Uploaded ${uploaded}/${#FILES[@]} file(s) to profile '${PROFILE}'."
